[mysqld]
basedir=C:/mysql-26.7.0-winx64/mysql-26.7.0-winx64
datadir=C:/mysql-26.7.0-winx64/mysql-26.7.0-winx64/data
port=3306
character-set-server=utf8mb4
default-storage-engine=INNODB

[mysql]
default-character-set=utf8mb4
